apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    app: {{ include "scanner.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  selector:
    matchLabels:
      app: {{ include "scanner.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "scanner.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- with .Values.podAnnotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}

      containers:
      - name: {{ include "scanner.name" . }}
        image: {{ .Values.image }}
        env:
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          {{ if and .Values.autoPoll .Values.autoPoll.coolOffAfterTagCount }}
          - name: COOL_OFF_AFTER_TAG_COUNT
            value: {{ .Values.autoPoll.coolOffAfterTagCount | quote }}
          {{ end }}
          {{ if and .Values.autoPoll .Values.autoPoll.coolOffMilliseconds }}
          - name: COOL_OFF_MILLISECONDS
            value: {{ .Values.autoPoll.coolOffMilliseconds | quote }}
          {{ end }}
          {{ if and .Values.autoPoll .Values.autoPoll.maxConcurentScans }}
          - name: MAX_CONCURRENT_SCANS
            value: {{ .Values.autoPoll.maxConcurentScans | quote }}
          {{ end }}
          - name: LACEWORK_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
{{- if kindIs "string" .Values.config.lacework.integration_access_token }}
                name: {{ include "scanner.name" . }}-access-token
                key: scanner-access-token
{{- else }}
                name: {{ required "Secret name required for existing secret" .Values.config.lacework.integration_access_token.existingSecret.name }}
                key: {{ required "Key name required for existing secret" .Values.config.lacework.integration_access_token.existingSecret.key }}
{{- end }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: scanner-config-volume
          mountPath: /opt/lacework/config
{{- if (and (not .Values.config.registry_secret_name) .Values.config.registries) }}
        - name: registries
          mountPath: /registries
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
{{- end }}
      volumes:
      - name: "certs"
        secret:
            secretName: {{ .Values.name }}-certs
{{- if (and (not .Values.config.registry_secret_name) .Values.config.registries) }}
      - name: "registries"
        secret:
{{- if .Values.config.registry_secret_name }}
          secretName: {{ .Values.config.registry_secret_name }}
{{- else }}
          secretName: {{ include "scanner.name" . }}-registry-secrets
{{- end }}
{{- end }}
      - name: "scanner-config-volume"
        configMap:
          name: {{ include "scanner.fullname" . }}
